# Generated by Django 4.2.5 on 2023-09-26 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('сибирская', 'сибирская'), ('британская', 'британская'), ('лайка', 'лайка'), ('овчарка', 'овчарка'), ('попугай', 'попугай'), ('канарейка', 'канарейка'), ('черепаха', 'черепаха'), ('ящерица', 'ящерица'), ('хомяк', 'хомяк'), ('мышь', 'мышь')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Kind',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('кот', 'кот'), ('собака', 'собака'), ('птица', 'птица'), ('рептилия', 'рептилия'), ('грызун', 'грызун')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Medicines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('breed', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.breed')),
                ('diag', models.ManyToManyField(null=True, to='catalog.diagnosis')),
                ('kind', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.kind')),
                ('meds', models.ManyToManyField(null=True, to='catalog.medicines')),
            ],
        ),
        migrations.AddField(
            model_name='breed',
            name='kind',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.kind'),
        ),
    ]
